# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/toniebox-reverse-engineering/teddycloud:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Teddycloud"
  org.opencontainers.image.description: "Teddycloud"
  org.opencontainers.image.source: "https://github.com/baflo/home-assistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
