build_from:
  amd64: docker.io/gitea/act_runner:latest
  aarch64: docker.io/gitea/act_runner:latest
  armv7: docker.io/gitea/act_runner:latest

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Gitea Act Runner"
  org.opencontainers.image.description: "Home Assistant Add-on to run GitHub Actions via act_runner from Gitea"
  org.opencontainers.image.source: "https://github.com/dein-benutzername/homeassistant-gitea-act-runner"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.version: "0.1.0"
