name: "Gitea Act Runner"
version: "0.1.0-dev10"
slug: "gitea_act_runner"
description: "Runs GitHub Actions with Act as a Home Assistant add-on using Gitea Act Runner"
url: "https://github.com/dein-repo/homeassistant-gitea-act-runner"
arch:
  - amd64
  - aarch64
  - armv7

privileged:
  - BPF
  - CHECKPOINT_RESTORE
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - PERFMON
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME

init: true
startup: services
boot: auto
hassio_api: true
homeassistant_api: false
host_network: false

map:
  - config:rw
  - data:rw

schema:
  runner_name: str
  instance_url: str
  registration_token: str
  labels: [str]
options:
  runner_name: "gitea-act-runner"
  labels: []

