name: "Gitea Act Runner"
version: "0.1.0-dev18"
slug: "gitea_act_runner"
description: "Runs GitHub Actions with Act as a Home Assistant add-on using Gitea Act Runner"
url: "https://github.com/dein-repo/homeassistant-gitea-act-runner"
arch:
  - amd64
  - aarch64
  - armv7

init: false
startup: services
boot: auto

map:
  - config:rw
  - data:rw

schema:
  runner_name: str
  instance_url: str
  registration_token: str
  labels: [str]
options:
  runner_name: "gitea-act-runner"
  labels: []

