args:
  NTFY_VERSION: 2.12.0

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ntfy"
  org.opencontainers.image.description: "Send push notifications to your phone or desktop via scripts from any computer"
  org.opencontainers.image.source: "https://github.com/binwiederhier/ntfy"

