ARG BUILD_FROM
# hadolint ignore=DL3006

FROM linuxserver/tvheadend

ENV HOME="/data"

# Install base system
ARG BASHIO_VERSION="v0.16.2"
ARG TEMPIO_VERSION="2021.09.0"
RUN \
    set -o pipefail \
    \
    && curl -J -L -o /tmp/bashio.tar.gz \
        "https://github.com/hassio-addons/bashio/archive/${BASHIO_VERSION}.tar.gz" \
    && mkdir /tmp/bashio \
    && tar zxvf \
        /tmp/bashio.tar.gz \
        --strip 1 -C /tmp/bashio \
    \
    && mv /tmp/bashio/lib /usr/lib/bashio \
    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio \
    \
    && curl -L -s -o /usr/bin/tempio \
        "https://github.com/home-assistant/tempio/releases/download/${TEMPIO_VERSION}/tempio_${BUILD_ARCH}" \
    && chmod a+x /usr/bin/tempio 

COPY rootfs/ /
