name: paperless-ngx-ingress
panel_title: Paperless
panel_icon: mdi:file-document-multiple-outline
description: Embeds paperless-ngx with ingress in Home Assistant.
version: "0.2.3-15"
slug: paperless-ngx-ingress

arch:
  - amd64
  - i386

map:
  - share:rw

init: false

ingress: true
ingress_port: 666
watchdog: http://[HOST]:[PORT:666]

panel_admin: false

options:
  admin:
    username: null
    password: null
  consumption: 
    dir: paperless
    recursively: false
    subdirsAsTags: false
  login: manual
  hosts:
    - host: http://homeassistant.local:8123
  ocr_langs:
    - deu
  web_workers: 1
schema:
  admin:
    username: str
    password: str
  consumption:
    dir: str
    recursively: bool
    subdirsAsTags: bool
  login: list(admin|auto|manual)
  hosts:
    - host: url
  ocr_langs:
    - str
  web_workers: int(1,)

hassio_api: true
backup: cold
