# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Restic Backup"
  org.opencontainers.image.description: "Backup your HomeAssistant instance using Restic"
  org.opencontainers.image.source: "https://github.com/baflo/ha-restic-backup"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  RESTIC_VERSION: "0.16.4"