name: Apache Tika
description: The Apache Tika™ toolkit detects and extracts metadata and text from over a thousand different file types (such as PPT, XLS, and PDF). All of these file types can be parsed through a single interface, making Tika useful for search engine indexing, content analysis, translation, and much more. 
version: "0.0.1"
slug: apache-tika

arch:
  - amd64
  - i386

init: false

