name: "df"
version: "0.0.0-0"
slug: "df"
description: "Provides a service which returns the data usage of any folder."
arch:
  - amd64
  - armhf
  - armv7
  - i386
startup: services
environment:
  HTTP_PORT: "1234"
map:
  - homeassistant_config:ro
  - addon_config:ro
  - ssl:ro
  - addons:ro
  - backup:ro
  - share:ro
  - media:ro
  - all_addon_configs:ro
